### ISSUE TITLE
Infinite Loop in 2-player game of Omni-Ones & Cocoa Rainbow (6 Suits) 

### ISSUE THREAD

**Issue by rahsosprout** [hanabi/hanabi.github.io#829]
Typo "Rainbor"

Uncaught Error: Failed to find the "Cocoa Rainbor" suit in the "SUITS" map.
    at x (gameData.ts:18:11)
    at yf (drawCards.ts:600:27)
    at drawCards.ts:77:23
    at Cf (uiInit.ts:94:24)
    at uiInit.ts:28:5
    at gameCommands.ts:170:3
    at Object.init (websocketInit.ts:97:7)
    at gu.onMessage (Connection.ts:52:22)

**Comment by Zamiell** [comment]
@rahsosprout  please don't open website issues on this repository
